/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ForgotPasswordPayloadDTO {
  email: string;
}

export interface ResetPasswordPayloadDTO {
  email: string;
  newPassword: string;
}

export interface SigninPayloadDTO {
  email: string;
  password: string;
}

export interface SignupPayloadDTO {
  email: string;
  password: string;
  role: string;
}

export interface UpdateWalletDetailPayloadDTO {
  bio?: string;
  discordUserName?: string;
  email?: string;
  fullName?: string;
  instagramUserName?: string;
  profilePicUrl?: string;
  twitterUserName?: string;
  websiteLink?: string;
}

export interface VerifyOtpPayloadDTO {
  email: string;
  otp: number;
}

export interface WalletPayloadDTO {
  role: string;
  type: string;
  walletAddress: string;
}
