/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UpdateWalletDetailPayloadDTO {
  bio?: string;
  discordUserName?: string;
  email?: string;
  fullName?: string;
  instagramUserName?: string;
  profilePicUrl?: string;
  twitterUserName?: string;
  websiteLink?: string;
}

export interface WalletPayloadDTO {
  role: string;
  type: string;
  walletAddress: string;
}
