/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IndustryIdParamDTO {
  industryId: string;
}

export interface IndustryPayloadDTO {
  name: string;
}

export interface UpdateIndustryPayloadDTO {
  name: string;
}
