/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface TextToImagePayloadDTO {
  cfg_scale: number;
  height: number;
  samples: number;
  seed: number;
  steps: number;
  text_prompts: {
    text: string;
    weight: number;
  }[];
  width: number;
}
